# Generated by Django 5.1.3 on 2024-11-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_category_lesson_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['category', 'number'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
